spring.application.name=SecurityDemo

server.port =9090
jwt.secretKey = "afubvbkf94205bbbefvffj870bbbbbbbbbbbb67567bbvvk9vf3bbfu"
deploy.env = "development"

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update